name: my-module CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      # Run the script that returns the version from `module.json`
      # - name: Get Version
      #   shell: bash
      #   id: get-version
      #   run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      # Update the module.json version to match the tag
      - name: Update Version
        shell: bash
        id: set-version
        run: echo "::set-output name=version::$(node ./.github/workflows/set-version.js ${{ github.ref }})"

      - name: Update module.json
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'module.json'
          commit-msg: 'Update module.json version to ${{ github.ref_name }}'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: zip -r ./gurps-quick-reference-sheet.zip module.json gurps-quick-reference-sheet.js assets/ scripts/ styles/ templates/

      # Create an additional release for this version
      - name: Create Release
        id: create_versioned_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # set to false if you do not want to allow updates on existing releases
          name: Release ${{ github.ref_name }} # Use the version in the name
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json,./gurps-quick-reference-sheet.zip'
          tag: ${{ github.ref_name }} # Use the version as the tag

      - name: Create Latest Release
        id: create_latest_release
        uses: ncipollo/release-action@v1
        if: endsWith(${{ github.ref }}, 'master') # Only update the latest release when pushing to the master branch
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json,./gurps-quick-reference-sheet.zip'
          tag: latest
